// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAKT3G3TthUZR6zULpaUZu6YrVmvT59JiU',
    appId: '1:474011763806:web:0227f2525e82dc18f1a0cf',
    messagingSenderId: '474011763806',
    projectId: 'noisewatch-70f20',
    authDomain: 'noisewatch-70f20.firebaseapp.com',
    databaseURL: 'https://noisewatch-70f20-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'noisewatch-70f20.appspot.com',
    measurementId: 'G-JY0FC6GDFT',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCwnKejMPz3oYe40UZHIrUmuGfIvPqYF2E',
    appId: '1:474011763806:android:0b6125a446f6f93df1a0cf',
    messagingSenderId: '474011763806',
    projectId: 'noisewatch-70f20',
    databaseURL: 'https://noisewatch-70f20-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'noisewatch-70f20.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCLP4JK6CCWNR_LYRNzS8lp3vtFPOHUGJc',
    appId: '1:474011763806:ios:34a07505fc72ffd4f1a0cf',
    messagingSenderId: '474011763806',
    projectId: 'noisewatch-70f20',
    databaseURL: 'https://noisewatch-70f20-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'noisewatch-70f20.appspot.com',
    iosClientId: '474011763806-n52jvec3dkifcg79qjh7nfu4kt44g57f.apps.googleusercontent.com',
    iosBundleId: 'com.example.noisewatch',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCLP4JK6CCWNR_LYRNzS8lp3vtFPOHUGJc',
    appId: '1:474011763806:ios:34a07505fc72ffd4f1a0cf',
    messagingSenderId: '474011763806',
    projectId: 'noisewatch-70f20',
    databaseURL: 'https://noisewatch-70f20-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'noisewatch-70f20.appspot.com',
    iosClientId: '474011763806-n52jvec3dkifcg79qjh7nfu4kt44g57f.apps.googleusercontent.com',
    iosBundleId: 'com.example.noisewatch',
  );
}
